
import Header from "@/components/Header";
import Footer from '@/components/Footer';

export const metadata = {
  title: "Fotado",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <main className='flex-fill'>
        {children}
      </main>
      <Footer />
    </>
  );
}

