
import DeskHeader from "@/components/Header/DeskHeader";
import Footer from '@/components/Footer/Footer';
import MobileHeader from "@/components/Header/MobileHeader";



export const metadata = {
  title: "Fotado",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <>
      <div className="d-lg-block d-none">
        <DeskHeader />
      </div>
      <div className="d-block d-lg-none">
        <MobileHeader />
      </div>
      <main className='flex-fill'>
        {children}
      </main>
      <Footer />
    </>
  );
}

